licenses(['notice'])
package(default_visibility = ['//visibility:public'])

cc_library(
    name = 'os',
    srcs = [
        'os.cpp',
        'path.cpp',
    ],
    hdrs = [
        'os.h',
        'path.h',
    ],
)

#cc_test(
    #name = 'gtest_path',
    #srcs = [
        #'gtest_path.cpp',
    #],
    #deps = [
        #':os',
        #'//third_party/gtest:gtest_main',
    #],
#)
