licenses(['notice'])
package(default_visibility = ['//visibility:public'])

cc_library(
    name = 'utils',
    srcs = [
        'UStringTools.cpp',
    ],
    hdrs = [
        'UStringTools.h',
    ],
    deps = [
        '//external:icu',
        '//' + PACKAGE_NAME + '/os:os',
    ],
)
