# This file is generated by running `yapf` on bad.py.  The configuration is stored as
# $ROOT/.style.yapf.

call_func_that_takes_a_dict({
    'key1': 'value1',
    'key2': 'value2',
})
from a_very_long_or_indented_module_name_yada_yad import (long_argument_1,
                                                          long_argument_2,
                                                          long_argument_3)
1 + 2 * 3 - 4 / 5

x = {'a': 37, 'b': 42, 'c': 927}

y = 'hello ' 'world'
z = 'hello ' + 'world'
a = 'hello {}'.format('world')


class foo(object):

    def f(self):
        return 37 * -+2

    def g(self, x, y=42):
        return y


def f(a):
    return 37 + -+a[42 - x:y**3]


foo(karg=val1, karg2=val2)

if ddsfdsfdsffffffffffffffffffffffffffffffffffffffffffffffff and yyyyyyyyyyyyyyyyyyyyyyzxcvcxvxcvczxvcxzv:
    d = 3

# The following data block should stay untouched.
BAZ = {
    (1, 2, 3, 4),
    (5, 6, 7, 8),
    (9, 10, 11, 12),
}
